#!/bin/bash

CONTAINER_NAME=$1
IMAGE_NAME=$2
DEV_NAME=opt4smart
WS_NAME=crazychoir_ws

# Authorization
xhost +

# Run and create container
docker run -it \
  --privileged \
  --gpus=all \
  --network=host \
  --shm-size=200mb \
  --env="DISPLAY" \
  --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
  --volume=./$WS_NAME:/home/$DEV_NAME/$WS_NAME \
  --name $CONTAINER_NAME \
  $IMAGE_NAME
